### ISSUE TITLE
Is this repository still needed?

### ISSUE THREAD

**Issue by probonopd** [BobanSpasic/MDX_Vault#2]
Is this repository still needed once 
https://github.com/BobanSpasic/MDX_PerfConv/
can do all the conversions on-the-fly upon each `git push`?

Personally I like using MDX_PerfConv better than this repository, because one sees which input produces which output. In this repository, one doesn't see how the ini files were made, whether there was something changed by hand, etc.

**Comment by BobanSpasic** [comment]
Honestly, I don't like having Yamaha's (copyrighted) files there at all.
At the moment, there are just files that can easily be found on the internet, but nothing that I've got recently bought, like the DX7II Cartridges.

With performance.ini files, I am not so worried.
